version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    container_name: app-koi
    ports:
      - "8082:8000"
    volumes:
      - .:/var/www
      - ./node_modules:/var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:...
    depends_on:
      - db
    command: ["sh", "-c", "npm install && npm run production && php artisan serve --host=0.0.0.0 --port=8000"]

  db:
    image: mysql:8.0
    container_name: laravel1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel1
    volumes:
      - mysql_data:/var/lib/mysql
    #   - ./database.sql:/docker-entrypoint-initdb.d/laravel1.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel1-db
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
